label: 'GA4GH :: Discovery'
name: Beacon
description: |
  A Work Stream of the Global Alliance for Genomics and Health
keywords: genomics, cloud, Beacon, DNA, sharing, GA4GH
site_domain_name: ga4gh-discovery.github.io
baseurl: ""
site_parent_link: 'https://ga4gh.org'
github_organisation: ga4gh-discovery
show_downloads: true
future: true

# instructions for processing specific directories

include:
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

collections_dir: pages
collections:
  doc:
    output: true
    permalink: /doc/:path/
  beacon:
    output: true
    permalink: /beacon/:path/
  networks:
    output: true
    permalink: /networks/:path/
  search:
    output: true
    permalink: /search/:path/
  schemablocks:
    output: true
    permalink: /schemablocks/:path/
  people:
    output: true
    permalink: /people/:path/
  minutes:
    output: true
    permalink: /minutes/:path/

# navigation blocks can be used to separate different categories and add e.g.
# external link block(s), in combination with a properly modified layout
nav_cat_blocks:
  General: 'General,categories,hide'
  Products: 'Workstream Products,categories,show'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

General:
  news: News
  people: Participants
  howto: 'Examples, Guides & FAQ'
  minutes: 'Meeting minutes'
  contact: Contacts

Products:
  beacon: 'Beacon'
  networks: 'Networks'
  schemablocks: 'GA4GH SchemaBlocks'
  search: 'Search'

categories-date-sorted:
  - news
  - minutes

tags-date-sorted:
  - releases
  - press

# tag_cloud items
cloud_tags:
  - admins
  - Beacon
  - contacts
  - contributors
  - developers
  - GA4GH
  - leads
  - press
  - networks
  - registry
  - releases
  - SchemaBlocks
  - SearchAPI
  - website
  - roadmap

related_sites:
  'Beacon Project': 'http://ga4gh-beacon.github.io'
  'GA4GH SchemaBlocks': 'http://schemablocks.org'
  GA4GH: 'http://www.ga4gh.org'
  'Beacon<span style="vertical-align: super; color: red; font-weight: 800;">+</span>': 'http://beacon.progenetix.org'
  'beacon-network.org': 'http://beacon-network.org'

github_projects:
  'Discovery': 'http://github.com/ga4gh-discovery/'
  'ELIXIR Beacon': 'http://github.com/ga4gh-beacon/'
  'SchemaBlocks': 'http://github.com/ga4gh-schemablocks/'

# additional Jekyll instructions

plugins:
 - jekyll-seo-tag
type: website
navigation_max_items: 4 # number of shown links in current category
emptyArray: []          # dummy element for array initialisation
